version: '3'

services:
  # admin:
  #   build:
  #     context: ./admin/server/
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   networks: 
  #     - nodeapp-network

  upload-processor:
    build:
      context: ./upload-processor
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: [ "pm2-runtime", "start", "npm", "--", "start" ]
    networks: 
      - nodeapp-network

  redis:
    image: redis:alpine
    ports:
     - "6379:6379"
    networks: 
      - nodeapp-network
    
networks:
  nodeapp-network:
    driver: bridge