version: '3.2'

services:
  # admin:
  #   build:
  #     context: ./admin/server/
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   networks: 
  #     - nodeapp-network

  upload-processor:
    build:
      context: ./upload-processor
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: [ "pm2-runtime", "start", "npm", "--", "start" ]
    networks: 
      - nodeapp-network

  redis:
    image: redis:alpine
    ports:
     - "6379:6379"
    networks: 
      - nodeapp-network
    
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "P@22word"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - type: volume
        source: dbdata
        target: /var/opt/mssql
    
networks:
  nodeapp-network:
    driver: bridge

volumes:
  dbdata:
    driver: local