service: user-signup

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  memorySize: 512


functions:
  create:
    handler: user-signup/handler.signup
    events:
      - http:
          path: signup/{clientCode}
          method: post
          cors: true
                
