service: user-signup

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  memorySize: 512


functions:
  create:
    handler: user-signup/handler.signup
    events:
      - http:
          path: signup/{clientCode}
          method: post
          cors: true

  saveTable:
    handler: dest-tables/handler.saveTableColumnDefs
    events:
      - http:
          path: tables/
          method: post
          cors: true          

  createTemplate:
    handler: templates/handler.saveTemplate
    events:
      - http:
          path: templates/
          method: post
          cors: true          

  updateTemplate:
    handler: templates/handler.saveTemplate
    events:
      - http:
          path: templates/{templateId}
          method: post
          cors: true          

  createTemplateColumn:
    handler: templates/handler.saveTemplateColumnHandler
    events:
      - http:
          path: templates/{templateId}/columns
          method: post
          cors: true          
                
  updateTemplateColumn:
    handler: templates/handler.saveTemplateColumnHandler
    events:
      - http:
          path: templates/{templateId}/columns/{templateColumnId}
          method: post
          cors: true          
                
