export default {
    SHOW_LOADING: 'SHOW_LOADING',
    SET_EXISTING_TABLES: 'LOAD_EXISTING_ABLES',
    LOAD_DESTTABLES: 'LOAD_DESTTABLES',
    MAP_TO_DESTTABLE: 'MAP_TO_DESTTABLE',
    UNMAP_FROM_DESTTABLE: 'UNMAP_FROM_DESTTABLE'
}