service: file-receiving

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  memorySize: 512
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
  create:
    handler: handler.upload
    events:
      - http:
          path: files
          method: post
          cors: true
