export default {
    SHOW_LOADING: 'SHOW_LOADING',
    LOAD_TEMPLATES: 'LOAD_TEMPLATES',
    LOAD_TEMPLATE_DETAIL: 'LOAD_TEMPLATE_DETAIL',
    LOAD_DESTTABLES: 'LOAD_TABLES',
    SET_MAPPING_DESTTABLES: 'SET_MAPPING_DESTTABLES'
}