service: file-processing

provider:
  name: aws
  runtime: dotnetcore2.1
  stage: dev
  region: us-east-1
  memorySize: 512
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
  process:
    handler: FileProcessing::FileProcessing.Function::Process
    events:
      - s3:
          bucket: file-to-process
          event: s3:ObjectCreated:*
