service: file-processing

provider:
  name: aws
  runtime: dotnetcore2.1
  stage: dev
  region: us-east-1
  memorySize: 512
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

package:
  individually: true

functions:
  process:
    handler: FileProcessing::FileProcessing.Functions::Process
    events:
      - s3:
          bucket: file-to-process
          event: s3:ObjectCreated:*
    package:
      artifact: bin/release/netcoreapp2.1/file-processing.zip