version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - cd data-loader
      - echo Current directory is `pwd`
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t data-loader:latest .
      - docker tag data-loader:latest 767567474540.dkr.ecr.us-east-1.amazonaws.com/data-loader:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 767567474540.dkr.ecr.us-east-1.amazonaws.com/data-loader:latest
      - echo Writing image definitions file...
      - printf '[{"name":"data-loader-container","imageUri":"%s"}]' 767567474540.dkr.ecr.us-east-1.amazonaws.com/data-loader:latest > imagedefinitions.json
artifacts:
  files: data-loader/imagedefinitions.json
